site_name: ML at the Edge in Mali
#site_url: https://edgemali.github.io

nav:
  - 2023:
    - ./2023/index.en.md
    - ./2023/program.en.md
    - ./2023/application.en.md
    - ./2023/call_paper.en.md
    - ./2023/competition.en.md
    - ./2023/sponsors.en.md
    - ./2023/faqs.en.md

theme:
  language: en
  name: material
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.top

plugins:
  - search
  - i18n :
      default_language: en
      languages:
        en: English
        fr: Français
  - social:
      cards_font: Roboto
      cards_dir: .cache/plugin/social
      cards_color:
        fill: "#0FF1CE" 
        text: "#FFFFFF"

copyright: Copyright &copy; 2023 RobotsMali. Proudly made with Material for MkDocs.
extra:

  generator: false

  version:
    provider: mike

  social:
    - icon: fontawesome/brands/facebook
      link: 
      name: RobotsMali on Facebook

    - icon: fontawesome/brands/instagram
      link: 
      name: RobotsMali on Instagram
    
    - icon: fontawesome/brands/linkedin
      link: 
      name: RobotsMali on Linkedin

    - icon: fontawesome/brands/github
      link: 
      name: RobotsMali on Github

    - icon: fontawesome/solid/paper-plane
      link: mailto:<email-address>
      name: Our Email

markdown_extensions:
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
