name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material \
          CairoSVG==2.6.0 mkdocs-i18n==0.4.4 \
          mkdocs-static-i18n==0.53 Pillow==9.4.0
      - run: mkdocs build
      - run: mkdocs gh-deploy --force

